# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               黑白先森
tagline:             'blog'
description:         '我的微博 <a href="http://weibo.com/mrheibai" target="_blank">@mrheibai</a>.'
url:                 http://heibaisir.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              黑白先森
  url:               http://weibo.com/mrheibai
  email:             cubyee@126.com

# Custom vars
version:             1.0.0
